#!/bin/bash
# for linux build
gcc -g -IInclude -Llib src/main.c -lGeneralGoodLinux -lSDLFontCacheLinux -lm -lpthread -lSDL2_image -lSDL2_ttf -lSDL2_mixer `sdl2-config --cflags --libs` -Llib -lluaLinux -ldl -o build/a.exe
