# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sf_C/Higurashi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sf_C/Higurashi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_C/Higurashi/CMakeFiles /media/sf_C/Higurashi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_C/Higurashi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HIGURASHI

# Build rule for target.
HIGURASHI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HIGURASHI
.PHONY : HIGURASHI

# fast build rule for target.
HIGURASHI/fast:
	$(MAKE) -f CMakeFiles/HIGURASHI.dir/build.make CMakeFiles/HIGURASHI.dir/build
.PHONY : HIGURASHI/fast

#=============================================================================
# Target rules for targets named HIGURASHI.self

# Build rule for target.
HIGURASHI.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HIGURASHI.self
.PHONY : HIGURASHI.self

# fast build rule for target.
HIGURASHI.self/fast:
	$(MAKE) -f CMakeFiles/HIGURASHI.self.dir/build.make CMakeFiles/HIGURASHI.self.dir/build
.PHONY : HIGURASHI.self/fast

#=============================================================================
# Target rules for targets named HIGURASHI.vpk

# Build rule for target.
HIGURASHI.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HIGURASHI.vpk
.PHONY : HIGURASHI.vpk

# fast build rule for target.
HIGURASHI.vpk/fast:
	$(MAKE) -f CMakeFiles/HIGURASHI.vpk.dir/build.make CMakeFiles/HIGURASHI.vpk.dir/build
.PHONY : HIGURASHI.vpk/fast

src/main.obj: src/main.c.obj

.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) -f CMakeFiles/HIGURASHI.dir/build.make CMakeFiles/HIGURASHI.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/HIGURASHI.dir/build.make CMakeFiles/HIGURASHI.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/HIGURASHI.dir/build.make CMakeFiles/HIGURASHI.dir/src/main.c.s
.PHONY : src/main.c.s

src/soloud_c.obj: src/soloud_c.cpp.obj

.PHONY : src/soloud_c.obj

# target to build an object file
src/soloud_c.cpp.obj:
	$(MAKE) -f CMakeFiles/HIGURASHI.dir/build.make CMakeFiles/HIGURASHI.dir/src/soloud_c.cpp.obj
.PHONY : src/soloud_c.cpp.obj

src/soloud_c.i: src/soloud_c.cpp.i

.PHONY : src/soloud_c.i

# target to preprocess a source file
src/soloud_c.cpp.i:
	$(MAKE) -f CMakeFiles/HIGURASHI.dir/build.make CMakeFiles/HIGURASHI.dir/src/soloud_c.cpp.i
.PHONY : src/soloud_c.cpp.i

src/soloud_c.s: src/soloud_c.cpp.s

.PHONY : src/soloud_c.s

# target to generate assembly for a file
src/soloud_c.cpp.s:
	$(MAKE) -f CMakeFiles/HIGURASHI.dir/build.make CMakeFiles/HIGURASHI.dir/src/soloud_c.cpp.s
.PHONY : src/soloud_c.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... HIGURASHI"
	@echo "... edit_cache"
	@echo "... HIGURASHI.self"
	@echo "... HIGURASHI.vpk"
	@echo "... rebuild_cache"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/soloud_c.obj"
	@echo "... src/soloud_c.i"
	@echo "... src/soloud_c.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

